version: "2"

volumes:
  mysql:
    driver: "local"
  phpmyadmin:
    driver: "local"

services:
    mysql:
        image: 'mysql:8.0.12'
        environment:
            MYSQL_DATABASE: sea_battle
            MYSQL_USER: sea_battle
            MYSQL_PASSWORD: sea_battle
            MYSQL_ROOT_PASSWORD: root
        container_name: mysql
        volumes:
            - ./mysql/conf.d:/etc/mysql/conf.d
        ports:
            - "8006:3306"

    sea_battle:
        image: alexdanilenko/docker_nginx
        container_name: sea_battle
        environment:
            ENVIRONMENT: dev
        volumes:
            - ./:/var/www/html
            - ./docker/nginx/vhost:/etc/nginx/sites-available
        ports:
            - "8888:80"
        depends_on:
            - mysql
        links:
            - mysql

    phpmyadmin:
        image: 'phpmyadmin/phpmyadmin:latest'
        container_name: phpmyadmin
        environment:
            PMA_ARBITRARY: 1
            MYSQL_USER: sea_battle
            MYSQL_PASSWORD: sea_battle
            MYSQL_ROOT_PASSWORD: root
        volumes:
            - /sessions
        ports:
            - "8080:80"
        links:
            - "mysql:db"
