version: "2"

services:
    lazer:
        build: ./docker/nginx
        container_name: lazer
        environment:
            ENVIRONMENT: dev
        volumes:
            - ./:/var/www/html
            - ./docker/nginx/vhost:/etc/nginx/sites-available
        ports:
            - "8888:80"
