version: "2"

services:
    qwe:
        build: ./docker/nginx
        container_name: qwe
        environment:
            ENVIRONMENT: dev
        volumes:
            - ./:/var/www/html
            - ./docker/nginx/vhost:/etc/nginx/sites-available
        ports:
            - "5000:80"
